### PR TITLE
When using disableBodyScroll, set stored scrollTo value to the initia…

### PR DESCRIPTION
**Pull request by bwshen**
…l scrolled position, as well as upon subsequent calls to init.

Hi Gromo, didn't find any information on the best way to submit proposed changes. If you'd prefer that i open up an issue or something else instead let me know.

I have the use case where i programatically scroll to a position initially. however when i mousewheel with disableBodyScroll: true, the mousewheel, assumes that initial scroll is 0, instead of the actual value and scrolls there.

thxs!

### CODE REVIEW

**Comment by gromo** [comment]
How do you change scroll position? Do you use jQuery scrollTop/scrollLeft? Can you prepare example with wrong behavior on jsFiddle.net using original jquery.scrollbar.js file?

**Comment by bwshen** [comment]
here's a jsfiddle:
https://jsfiddle.net/tjqgxkd9/3/

When you attempt to use the mousewheel, if you mousewheel down, you are scrolled to the top, if you mousewheel up, it doesn't scroll.

**Comment by bwshen** [comment]
apologies, try https://jsfiddle.net/tjqgxkd9/5/

**Comment by gromo** [comment]
Pretty interesting. If you use mousewheel over scrollbar it works correctly. Idea was that disableBodyScroll handles mousewheel and trigger the same event for scrollbars. I will look at the code in next few days

**Comment by bwshen** [comment]
something like this?

**Comment by gromo** [comment]
https://jsfiddle.net/tjqgxkd9/6/ - quick hack

**Comment by gromo** [comment]
But much better if you set scrollTop offset first and only then initialize scrollbar

**Pull request closed without merging**
